name = "gorkha-reels"
main = "share-worker.js"
type = "javascript"
compatibility_date = "2024-01-01"

[[routes]]
pattern = "gorkha-reels.pages.dev/share.html*"
zone_name = "gorkha-reels.pages.dev"

[build]
command = ""

[env.production]
vars = { APPWRITE_ENDPOINT = "https://fra.cloud.appwrite.io/v1", APPWRITE_PROJECT = "gorkhareels" }
